---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "ubuntu" 

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "ubuntu"  

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "ubuntu"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distributio_version == "centOS"

  - name: install apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "centOS"

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "centOS"

